### ISSUE TITLE
Cant run on mint

### ISSUE THREAD

**Issue by KatzeMau** [Transistor4aCPU/linux-gaming-setup#1]
root@Blade:/home/root/linux-gaming-setup# sh linux-gaming-setup
linux-gaming-setup: 77: [: /root/.steam: unexpected operator
Unable to init server: Verbindung ist gescheitert: Verbindungsaufbau abgelehnt

(zenity:4607): Gtk-WARNING **: 14:48:02.573: cannot open display:
linux-gaming-setup: 87: [: ==: unexpected operator
linux-gaming-setup: 94: linux-gaming-setup: Syntax error: end of file unexpected (expecting "then")
root@Blade:/home/root/linux-gaming-setup#

**Comment by Transistor4aCPU** [comment]
Don't run it as root. Run it  as normal user without sudo
